spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: 
    password: 
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: 

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            client-secret: 
            redirect-uri: 
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: 
            token-uri: 
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


